apiVersion: v1
kind: Service
metadata:
  name: quickstart-service-lb
  labels:
    app: quickstart
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart