apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  skuName: Standard_LRS
  location: westeurope