apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-pod-id
    aadpodidbinding: "<selector_label>"
  name: nginx-pod-id
spec:
  containers:
  - name: nginx-pod-id
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"         # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "<kv_name>"               # the name of the KeyVault
        keyvaultobjectnames: "<secret_name>"        # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret    # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "<rg_name>"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "<subscription_id>"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "<tenant_id>"                   # the tenant ID of the KeyVault